# Generated by Django 6.0.6 on 2026-07-16 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('Unidad', 'Unidad'), ('Kg', 'Kilogramo'), ('g', 'Gramo'), ('L', 'Litro'), ('mL', 'Mililitro'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Fardo', 'Fardo'), ('Saco', 'Saco'), ('Metro', 'Metro')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('operacion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('id_registro', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(db_column='id_usuario_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.insumo')),
                ('usuario_responsable', models.ForeignKey(db_column='id_usuario_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_insumos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'db_table': 'movimientos_insumos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_responsable', models.ForeignKey(db_column='id_usuario_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='programas_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_creador', models.ForeignKey(db_column='id_usuario_creador', on_delete=django.db.models.deletion.PROTECT, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.programa')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['-fecha_actividad'],
            },
        ),
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_actividad', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='core.actividad')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Actividad',
                'verbose_name_plural': 'Asignaciones de Actividades',
                'db_table': 'actividad_usuario',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'usuario'), name='pk_actividad_usuario')],
            },
        ),
        migrations.CreateModel(
            name='DetalleActividadInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.PROTECT, related_name='insumos_utilizados', to='core.actividad')),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='core.insumo')),
            ],
            options={
                'verbose_name': 'Insumo Utilizado',
                'verbose_name_plural': 'Insumos Utilizados',
                'db_table': 'detalle_actividad_insumo',
                'ordering': ['actividad'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'insumo'), name='pk_detalle_actividad_insumo')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.PROTECT, related_name='programas_asignados', to='core.beneficiario')),
                ('programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_asignados', to='core.programa')),
            ],
            options={
                'verbose_name': 'Asignación de Beneficiario',
                'verbose_name_plural': 'Asignaciones de Beneficiarios',
                'db_table': 'programa_beneficiario',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('programa', 'beneficiario'), name='pk_programa_beneficiario')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_programa', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='core.programa')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_programas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Programa',
                'verbose_name_plural': 'Asignaciones de Programas',
                'db_table': 'programa_usuario',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('programa', 'usuario'), name='pk_programa_usuario')],
            },
        ),
    ]
