# Generated by Django 6.0.6 on 2026-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadusuario',
            options={'ordering': ('-fecha_asignacion',), 'verbose_name': 'Asignación de Actividad', 'verbose_name_plural': 'Asignaciones de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='detalleactividadinsumo',
            options={'ordering': ('actividad',), 'verbose_name': 'Insumo Utilizado', 'verbose_name_plural': 'Insumos Utilizados'},
        ),
        migrations.AlterModelOptions(
            name='programabeneficiario',
            options={'ordering': ('-fecha_asignacion',), 'verbose_name': 'Asignación de Beneficiario', 'verbose_name_plural': 'Asignaciones de Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='programausuario',
            options={'ordering': ('-fecha_asignacion',), 'verbose_name': 'Asignación de Programa', 'verbose_name_plural': 'Asignaciones de Programas'},
        ),
        migrations.AlterField(
            model_name='programabeneficiario',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
