# Generated by Django 6.0.6 on 2026-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actividadusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ('-fecha_actividad',), 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ('-fecha_auditoria',), 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ('apellido', 'nombre'), 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='detalleactividadinsumo',
            options={'ordering': ('actividad', 'insumo'), 'verbose_name': 'Insumo Utilizado', 'verbose_name_plural': 'Insumos Utilizados'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ('nombre',), 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinsumo',
            options={'ordering': ('-fecha_movimiento',), 'verbose_name': 'Movimiento de Insumo', 'verbose_name_plural': 'Movimientos de Insumos'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ('nombre',), 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_actividad',
            field=models.DateTimeField(verbose_name='Fecha y hora de la actividad'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoinsumo',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
