# Generated by Django 6.0.6 on 2026-08-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_actividad_options_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(blank=True, choices=[('CREAR_PROGRAMA', 'Crear programa'), ('EDITAR_PROGRAMA', 'Editar programa'), ('DESACTIVAR_PROGRAMA', 'Desactivar programa')], max_length=50, null=True),
        ),
    ]
