# Generated by Django 6.0.6 on 2026-08-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR_PROGRAMA', 'Crear programa'), ('EDITAR_PROGRAMA', 'Editar programa'), ('DESACTIVAR_PROGRAMA', 'Desactivar programa'), ('ELIMINAR_PROGRAMA', 'Eliminar programa')], max_length=50),
        ),
    ]
