# Generated by Django 6.0.6 on 2026-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR_PROGRAMA', 'Crear programa'), ('EDITAR_PROGRAMA', 'Editar programa'), ('DESACTIVAR_PROGRAMA', 'Desactivar programa'), ('ELIMINAR_PROGRAMA', 'Eliminar programa'), ('CREAR_ACTIVIDAD', 'Crear actividad'), ('EDITAR_ACTIVIDAD', 'Editar actividad'), ('DESACTIVAR_ACTIVIDAD', 'Desactivar actividad'), ('CREAR_BENEFICIARIO', 'Crear beneficiario'), ('EDITAR_BENEFICIARIO', 'Editar beneficiario'), ('DESACTIVAR_BENEFICIARIO', 'Desactivar beneficiario')], max_length=50),
        ),
    ]
