# Generated by Django 6.0.6 on 2026-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR_PROGRAMA', 'Crear programa'), ('EDITAR_PROGRAMA', 'Editar programa'), ('DESACTIVAR_PROGRAMA', 'Desactivar programa'), ('ELIMINAR_PROGRAMA', 'Eliminar programa'), ('CREAR_ACTIVIDAD', 'Crear actividad'), ('EDITAR_ACTIVIDAD', 'Editar actividad'), ('DESACTIVAR_ACTIVIDAD', 'Desactivar actividad'), ('CREAR_BENEFICIARIO', 'Crear beneficiario'), ('EDITAR_BENEFICIARIO', 'Editar beneficiario'), ('DESACTIVAR_BENEFICIARIO', 'Desactivar beneficiario'), ('CREAR_ASIGNACION_BENEFICIARIO', 'Asignar beneficiario'), ('DESASIGNAR_BENEFICIARIO', 'Desasignar beneficiario'), ('CREAR_INSUMO', 'Crear insumo'), ('EDITAR_INSUMO', 'Editar insumo'), ('DESACTIVAR_INSUMO', 'Desactivar insumo'), ('REGISTRAR_ENTRADA_INSUMO', 'Registrar entrada de insumo'), ('REGISTRAR_SALIDA_INSUMO', 'Registrar salida de insumo'), ('REGISTRAR_CONSUMO_INSUMO', 'Registrar consumo de insumo')], max_length=50),
        ),
    ]
