# Generated by Django 6.0.6 on 2026-09-10 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditoria_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoinsumo',
            index=models.Index(fields=['insumo', 'fecha_movimiento'], name='idx_movimientos_insumo_fecha'),
        ),
    ]
