# Generated by Django 6.0.6 on 2026-09-10 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movimientoinsumo_idx_movimientos_insumo_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['fecha_auditoria'], name='idx_auditoria_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario_responsable'], name='idx_auditoria_usuario'),
        ),
    ]
