# Generated by Django 6.0.6 on 2026-08-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_usuario_cedula_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
