from .programa_admin import *
from .actividad_admin import *
from .beneficiario_admin import *
from .insumo_admin import *
from .movimiento_insumo_admin import *
from .programa_usuario_admin import *
from .actividad_usuario_admin import *
from .programa_beneficiario_admin import *
from .detalle_actividad_insumo_admin import *
from .auditoria_admin import *